[Interface]
PrivateKey = <mL9RJuDiHAC6tvlv+X2byyVPTGT6heC2qIedxLYrH3g=>
Address = 10.0.0.1/24
ListenPort = 51820

[Peer]
PublicKey = <N6wdDp8755P0nsczfZOvm/12ap42ILDCRVX97ODerWw=>
AllowedIPs = 10.0.0.2/32